-- Run this entire file in the Supabase SQL Editor

-- Users table (stores Strava OAuth tokens)
create table if not exists users (
  id uuid primary key default gen_random_uuid(),
  strava_id bigint unique not null,
  strava_access_token text not null,
  strava_refresh_token text not null,
  strava_token_expires_at timestamptz not null,
  name text,
  profile_photo_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Actual runs synced from Strava
create table if not exists actual_runs (
  id serial primary key,
  user_id uuid references users(id) on delete cascade,
  strava_activity_id bigint unique not null,
  run_date date not null,
  distance_km numeric(6,2) not null,
  moving_time_seconds int not null,
  pace_min_per_km numeric(5,2) not null,
  average_heartrate numeric(5,1),
  max_heartrate numeric(5,1),
  name text,
  created_at timestamptz default now()
);

-- AI suggestions generated by Claude
create table if not exists ai_suggestions (
  id serial primary key,
  user_id uuid references users(id) on delete cascade,
  week_number int not null,
  suggestion text not null,
  context jsonb,
  generated_at timestamptz default now()
);

-- Indexes for common queries
create index if not exists actual_runs_user_date on actual_runs(user_id, run_date desc);
create index if not exists ai_suggestions_user_week on ai_suggestions(user_id, week_number desc);
